version: "3"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    networks:
      - samplephpwebsite_default
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    networks:
      - samplephpwebsite_default
      
networks:
  samplephpwebsite_default:
    driver: bridge
