version: "3"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    networks:
      - samplephpwebsite_default
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - samplephpwebsite_default
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: sdrugntqqsciur
      MYSQL_DATABASE: db
      MYSQL_USER: php_user
      MYSQL_PASSWORD: sdrugntqqsciur
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mariadb/data/db:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - samplephpwebsite_default
  jenkins:
    build:
      context: ./docker/jenkins
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home 

networks:
  samplephpwebsite_default:
    driver: bridge
